### ISSUE TITLE
HipChat plugin loses global configuration on Jenkins restart 

### ISSUE THREAD

**Issue by conf** [jlewallen/jenkins-hipchat-plugin#18]
I.e. I have to enter each time hipchat token, room name and jenkins url.
I use Jenkins 1.454 on Debian squeeze with HipChat plugin 0.1.3.

**Comment by darrinholst** [comment]
I think [this](https://github.com/jlewallen/jenkins-hipchat-plugin/pull/17) fixes it, but I'm having a maven problem at the moment trying to get the latest pushed up to the jenkins repo.

http://maven.glassfish.org seems to be down and it's needed by the build process that uploads it. If it's not fixed by tomorrow I'll look for a work around.

**Comment by conf** [comment]
Thanks! Will try as soon new version will be available :)

**Comment by darrinholst** [comment]
version 1.0.4 has been pushed out now, give that one a try.

**Comment by conf** [comment]
Works great! Thanks, that was fast! :)

**Comment by hawknewton** [comment]
Hey darrinhoist, this'll help: http://groups.google.com/group/jenkinsci-dev/browse_thread/thread/512cef98ef64dfcd ...  Looks like maven.glassfish.org has been down for a while.
